scrape_configs:
  - job_name: 'BookMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['34.168.74.25:80','host.docker.internal:80']
        labels:
          application: 'book'